# Generated by Django 4.2.5 on 2023-09-09 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_remove_booking_number_of_guests_booking_no_of_guests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='no_of_guests',
            new_name='number_of_guests',
        ),
    ]
