# Generated by Django 4.2.5 on 2023-09-09 11:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_rename_no_of_guests_booking_number_of_guests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='number_of_guests',
            new_name='no_of_guests',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
