# Generated by Django 4.2.5 on 2023-09-13 08:51

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_booking_reservation_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
